Update devopsworkspace.yml

diff --git a/.github/workflows/devopsworkspace.yml b/.github/workflows/devopsworkspace.yml
--- a/.github/workflows/devopsworkspace.yml
+++ b/.github/workflows/devopsworkspace.yml
@@ -27,3 +27,11 @@ jobs:
 
       - name: Run tests
         run: pytest
+      - name: Run Flask App 
+        run: |
+             python app.py &
+             sleep 5
+      - name: checking the app 
+        run: |
+          curl -s http://127.0.0.1:5000 || echo "Flask app failed to start!"
+           
